name: covid19_analytics_app
description: An application that displays the analytics of COVID-19.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  date_format: ^1.0.8
  pull_to_refresh: ^1.5.7
  charts_flutter: ^0.9.0
  google_maps_flutter: ^0.5.27
  geolocator: ^5.3.1
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  localstorage: ^3.0.2+5

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_styles/

  fonts:
    - family: GothamRndBold
      fonts:
        - asset: assets/fonts/GothamRnd-Bold.otf
    - family: GothamRndBook
      fonts:
        - asset: assets/fonts/GothamRnd-Book.otf
    - family: GothamRndLight
      fonts:
        - asset: assets/fonts/GothamRnd-Light.otf
    - family: GothamRndMedium
      fonts:
        - asset: assets/fonts/GothamRnd-Medium.otf
